name: 'EditorLint'
description: 'Validates and fixes files according to .editorconfig rules'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  # Expected parameters from proscia-techops workflows
  fix:
    description: 'Automatically fix violations instead of just reporting them'
    required: false
    default: 'false'

  config:
    description: 'Path to custom .editorconfig file (optional)'
    required: false
    default: ''

  exclude:
    description: 'Comma-separated list of glob patterns to ignore (e.g. "*.tmp,node_modules/**")'
    required: false
    default: ''

  reporter:
    description: 'Output format: default, tabular, json, quiet, github'
    required: false
    default: 'default'

  token:
    description: 'GitHub token for API access (when using github reporter or pr-comment)'
    required: false
    default: ''

  pr-comment:
    description: 'Post PR comments with violation details (requires token)'
    required: false
    default: 'false'

  pr-comment-header:
    description: 'Header text for PR comments'
    required: false
    default: '## 📝 EditorLint Results'

  # Additional parameters for flexibility
  version:
    description: 'Version of editorlint to use (e.g. "1.0.0" or "latest")'
    required: false
    default: 'latest'

  args:
    description: 'Custom arguments to pass to editorlint (e.g. "--fix --output json src/"). When provided, overrides structured inputs except path.'
    required: false
    default: ''

  path:
    description: 'Path to file or directory to validate'
    required: false
    default: '.'

  recurse:
    description: 'Process files recursively in directories'
    required: false
    default: 'true'

  fail-on-violations:
    description: 'Fail the action if violations are found'
    required: false
    default: 'true'

  auto-commit:
    description: 'Automatically commit fixes when fix=true'
    required: false
    default: 'false'

  commit-message:
    description: 'Commit message for auto-committed fixes'
    required: false
    default: 'fix: auto-fix editorconfig violations'

  git-user-name:
    description: 'Git user name for auto-commits'
    required: false
    default: 'github-actions[bot]'

  git-user-email:
    description: 'Git user email for auto-commits'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'

  # Legacy parameter names for backward compatibility
  config-file:
    description: 'Path to custom .editorconfig file (legacy - use config instead)'
    required: false
    default: ''

  output-format:
    description: 'Output format (legacy - use reporter instead)'
    required: false
    default: 'default'

outputs:
  violations-found:
    description: 'Whether any violations were found (true/false)'

  files-processed:
    description: 'Number of files processed'

  files-fixed:
    description: 'Number of files fixed (when fix=true)'

runs:
  using: 'composite'
  steps:
    - name: Install editorlint
      shell: bash
      run: ${{ github.action_path }}/install.sh
      env:
        INPUT_VERSION: ${{ inputs.version }}
        RUNNER_OS: ${{ runner.os }}
        RUNNER_ARCH: ${{ runner.arch }}

    - name: Run editorlint
      id: lint  
      shell: bash
      run: ${{ github.action_path }}/run.sh
      env:
        INPUT_ARGS: ${{ inputs.args }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_CONFIG: ${{ inputs.config }}
        INPUT_CONFIG_FILE: ${{ inputs.config-file }}
        INPUT_RECURSE: ${{ inputs.recurse }}
        INPUT_FIX: ${{ inputs.fix }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_OUTPUT_FORMAT: ${{ inputs.output-format }}
        INPUT_EXCLUDE: ${{ inputs.exclude }}
        INPUT_FAIL_ON_VIOLATIONS: ${{ inputs.fail-on-violations }}
        INPUT_AUTO_COMMIT: ${{ inputs.auto-commit }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_GIT_USER_NAME: ${{ inputs.git-user-name }}
        INPUT_GIT_USER_EMAIL: ${{ inputs.git-user-email }}

    - name: Create or Update PR Comment
      if: inputs.pr-comment == 'true' && inputs.token != '' && github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ inputs.token }}
        issue-number: ${{ github.event.pull_request.number }}
        comment-id: editorlint-results
        edit-mode: replace
        body: |
          ${{ inputs.pr-comment-header }}
          
          ${{ env.VIOLATIONS_FOUND == 'true' && env.FILES_FIXED != '0' && inputs.fix == 'true' && format('✅ **Fixed {0} files with EditorConfig violations**

          The following files were automatically fixed:
          ```
          {1}
          ```

          Files processed: {2}
          Files fixed: {3}', env.FILES_FIXED, env.EDITORLINT_OUTPUT, env.FILES_PROCESSED, env.FILES_FIXED) || env.VIOLATIONS_FOUND == 'true' && format('❌ **EditorConfig violations found**

          ```
          {0}
          ```

          Files processed: {1}
          Violations found: {2}

          Run with `fix: true` to automatically fix these issues.', env.EDITORLINT_OUTPUT, env.FILES_PROCESSED, env.VIOLATIONS_FOUND) || format('✅ **No EditorConfig violations found**

          Files processed: {0}
          All files comply with .editorconfig rules.', env.FILES_PROCESSED) }}